name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Download and set up Android SDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip -d android-sdk

        echo "ANDROID_HOME=$PWD/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$PWD/android-sdk" >> $GITHUB_ENV

        yes | android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$PWD/android-sdk "tools" "platform-tools" "build-tools;34.0.0" "platforms;android-33"

    - name: Initialize Gradle Wrapper
      working-directory: ./MyAndroidApp
      run: |
        gradle wrapper --gradle-version 8.0

    - name: Build APK
      working-directory: ./MyAndroidApp
      run: |
        ./gradlew assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: MyAndroidApp/app/build/outputs/apk/debug/app-debug.apk
