name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Set up Android NDK
      uses: android-actions/setup-ndk@v2
      with:
        ndk-version: '23.1.7779620'

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21

    - name: Build
      run: cmake --build build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: myandroidapp
        path: build/myandroidapp
